export const AvailableFeedTypes = {
  PELLETS: 'PELLETS',
  SKRETTING: 'SKRETTING',
  COPPENS: 'COPPENS',
  TOP_FEEDS: 'TOP_FEEDS',
  BLUE_CROWN: 'BLUE_CROWN',
  VITAL_FEEDS: 'VITAL_FEEDS',
  ALLER_AQUA: 'ALLER_AQUA',
  HYBRID_CATFISH_FEED: 'HYBRID_CATFISH_FEED',
  AQUALIS: 'AQUALIS',
  ECOFLOAT: 'ECOFLOAT',
  RAANAN: 'RAANAN',
  DURANTE: 'DURANTE',
  VITAL_FEED: 'VITAL_FEED',
  TOPFEED: 'TOPFEED',
  ANIMAL_CARE: 'ANIMAL_CARE',
  ZEIGLER: 'ZEIGLER',
  CHIKUN_FEED: 'CHIKUN_FEED',
  AMO_BYNG_FEED: 'AMO_BYNG_FEED',
  HYBRID_FEED: 'HYBRID_FEED',
  AF_FEED: 'AF_FEED',
}

export const MaintenanceActivityTypes = {
  LABOR: 'LABOR',
  CHEMICALS: 'CHEMICALS',
  EQUIPMENT: 'EQUIPMENT',
  ENERGY: 'ENERGY',
  CLEANING: 'CLEANING',
  REPAIRS: 'REPAIRS',
  DISINFECTION: 'DISINFECTION',
  OTHER: 'OTHER',
}

export const PelletSizes = ['0.5mm', '1.0mm', '2.0mm', '3.0mm', '4.0mm', '5.0mm', '6.0mm', '7.0mm', '8.0mm']
