/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: ['class'],
  content: ['./src/**/*.{ts,tsx}'],
  theme: {
    container: {
      center: true,
      padding: '2rem',
      screens: {
        '2xl': '1400px',
      },
    },
    extend: {
      colors: {
        primary: {
          1: 'var(--primary-1)',
          2: 'var(--primary-2)',
          3: 'var(--primary-3)',
          4: 'var(--primary-4)',
          5: 'var(--primary-5)',
          6: 'var(--primary-6)',
          7: 'var(--primary-7)',
          8: 'var(--primary-8)',
        },
        secondary: {
          1: 'var(--secondary-1)',
          2: 'var(--secondary-2)',
          3: 'var(--secondary-3)',
          4: 'var(--secondary-4)',
          5: 'var(--secondary-5)',
          6: 'var(--secondary-6)',
          7: 'var(--secondary-7)',
          8: 'var(--secondary-8)',
        },
        neutral: {
          1: 'var(--neutral-1)',
          2: 'var(--neutral-2)',
          3: 'var(--neutral-3)',
          4: 'var(--neutral-4)',
          5: 'var(--neutral-5)',
          6: 'var(--neutral-6)',
          7: 'var(--neutral-7)',
          8: 'var(--neutral-8)',
        },
        warning: {
          1: 'var(--warning-1)',
          2: 'var(--warning-2)',
          3: 'var(--warning-3)',
          4: 'var(--warning-4)',
          5: 'var(--warning-5)',
          6: 'var(--warning-6)',
          7: 'var(--warning-7)',
          8: 'var(--warning-8)',
        },
        error: {
          1: 'var(--error-1)',
          2: 'var(--error-2)',
          3: 'var(--error-3)',
          4: 'var(--error-4)',
          5: 'var(--error-5)',
          6: 'var(--error-6)',
          7: 'var(--error-7)',
          8: 'var(--error-8)',
        },
        success: {
          1: 'var(--success-1)',
          2: 'var(--success-2)',
          3: 'var(--success-3)',
          4: 'var(--success-4)',
          5: 'var(--success-5)',
          6: 'var(--success-6)',
          7: 'var(--success-7)',
          8: 'var(--success-8)',
        },
        info: {
          1: 'var(--info-1)',
          2: 'var(--info-2)',
          3: 'var(--info-3)',
          4: 'var(--info-4)',
          5: 'var(--info-5)',
          6: 'var(--info-6)',
          7: 'var(--info-7)',
          8: 'var(--info-8)',
        },
      },
      backgroundImage: {
       "auth-background": "url('./src/assets/images/background.png')",
      },
      borderRadius: {
        lg: 'var(--radius)',
        md: 'calc(var(--radius) - 2px)',
        sm: 'calc(var(--radius) - 4px)',
      },
      keyframes: {
        'accordion-down': {
          from: { height: 0 },
          to: { height: 'var(--radix-accordion-content-height)' },
        },
        'accordion-up': {
          from: { height: 'var(--radix-accordion-content-height)' },
          to: { height: 0 },
        },
      },
      animation: {
        'accordion-down': 'accordion-down 0.2s ease-out',
        'accordion-up': 'accordion-up 0.2s ease-out',
      },
    },
  },
  plugins: [require('tailwindcss-animate')],
}
